// ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SET_IS_SENDING_REQUEST = 'SET_IS_SENDING_REQUEST';

// FILE TYPES
export const GET_FILES = 'GET_FILES';
export const CLEAR_FILES = 'CLEAR_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const SET_LOADING_FILES = 'SET_LOADING';
